# Generated by Django 4.2.30 on 2026-05-29 15:35

import cloudinary.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=20)),
                ('source_type', models.CharField(choices=[('facebook_marketplace', 'Facebook Marketplace'), ('local', 'Local')], max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('facebook_listing_url', models.URLField(blank=True, max_length=500)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('base_rate_per_kg', models.DecimalField(decimal_places=2, help_text='KES per kg', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estimated_delivery_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uk_original_price', models.DecimalField(decimal_places=2, help_text='GBP — original UK listing price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sourcing_fee', models.DecimalField(decimal_places=2, help_text='KES', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_cost', models.DecimalField(decimal_places=2, help_text='KES — shipping for default method at listing time', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_logistics_cost', models.DecimalField(decimal_places=2, help_text='KES', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('profit_margin', models.DecimalField(decimal_places=2, help_text='KES — absolute margin', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_client_price', models.DecimalField(decimal_places=2, help_text='KES — price shown on storefront', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_shipping_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.shippingoption')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_breakdown', to='store.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='store_produ_is_acti_f9905c_idx'),
        ),
    ]
