# Generated by Django 4.2.30 on 2026-06-10 09:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_seed_shipping_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='pricebreakdown',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, help_text='GBP — absolute margin', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pricebreakdown',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, help_text='GBP — shipping for default method at listing time', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pricebreakdown',
            name='sourcing_fee',
            field=models.DecimalField(decimal_places=2, help_text='GBP', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pricebreakdown',
            name='transport_logistics_cost',
            field=models.DecimalField(decimal_places=2, help_text='GBP', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category'),
        ),
    ]
